name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docker-build:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Setup buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Docker buildx test
        run: |
          docker build .

